### ISSUE TITLE
俄罗斯转盘概率问题

### ISSUE THREAD

**Issue by Phantomdft** [sdyxxjj123/PcrDuel#2]
line 2781
 deadnum = int(math.floor( random.uniform(1,x) ))
 不可能达到6，导致 默认6发子弹的时候 先手胜率2/5，后手胜率3/5

**Comment by sdyxxjj123** [comment]
你好，请查看上一行，上一行中获取了子弹数量x之后对其进行了+1操作，这里的x实际上是子弹数+1，也就是random.uniform（1，7），因此是可以达到6的

**Comment by Phantomdft** [comment]
小丑竟是我自己.jpg
