### ISSUE TITLE
转发消息似乎会触发封控导致发不出

### ISSUE THREAD

**Issue by kokororin** [sdyxxjj123/PcrDuel#4]
作者大大您好，
转发消息似乎会触发风控导致发不出，测试了有一个qq号发不出，但是go-cqhttp不会报错，能不能加个配置支持下呢

**Comment by sdyxxjj123** [comment]
好的，下个版本会加入开关

**Comment by sdyxxjj123** [comment]
你好，新的版本（V5.6）已经加入了开关，欢迎测试，风控是QQ号本身的问题我无法解决，只能先加开关避免正常使用

**Comment by kokororin** [comment]
感谢
